name: eSyncPixelmon
main: com.aiyostudio.esyncpixelmon.SyncPixelmon
depend:
  - AyCore
loadbefore:
  - eSync
version: ${version}
api-version: 1.16
commands:
  syncpixelmon:
    description: Command for eSyncPixelmon.